wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.8
    start_time: 1672768120.889712
    t:
      1:
      - 1
      - 35
      - 55
      2:
      - 1
      - 35
      - 55
      3:
      - 2
      - 17
      - 18
      - 23
      - 34
      - 37
      4: 3.10.8
      5: 0.13.6
      8:
      - 4
      - 5
direction:
  desc: null
  value:
  - MINIMIZE
x:
  desc: null
  value: 1.2009041549418087
